In [3]:
import pandas as pd

dfNew = pd.read_excel('_CERTIFICATES1.xlsx', sheet_name='FICTIONAL')
dfO = pd.read_excel('_CERTIFICATES.xlsx', sheet_name='FICTIONAL')

diff = dfNew[~dfNew["ENROLLMENT"].isin(dfO["ENROLLMENT"]) ]
diff

        NAME BRANCH   ENROLLMENT     Certificate no.       Position
28  ANUJ PAL   CSBS  BTCB25O1021  MITS/MUN/2601/PC31  Participation

In [7]:
xls = pd.ExcelFile('_CERTIFICATES1.xlsx')
xls.sheet_names

['ORGANISING COMMITTEE',
 'FICTIONAL',
 ' INTERNATIONAL PRESS',
 'INTERNATIONAL ',
 ' INDIAN']

In [9]:
dfNewI = pd.read_excel('_CERTIFICATES1.xlsx', sheet_name='INTERNATIONAL ')
dfOI = pd.read_excel('_CERTIFICATES.xlsx', sheet_name='INTERNATIONAL ')

diffI = dfNewI[~dfNewI["ENROLLMENT"].isin(dfOI["ENROLLMENT"]) ]
diffI

                   NAME BRANCH   ENROLLMENT    CERTIFICATEE NO.           TYPE
35  RADHAKRISHNAN GUPTA  CIVIL  BTCE25O1088  MITS/MUN/2601/CP38  Participation
36        SRUSHTI RAWAL   AIDS  BTAD24O1067  MITS/MUN/2601/CP39  Participation