In [11]:
import pandas as pd

url = "https://official-joke-api.appspot.com/random_ten"
df = pd.read_json(url)
df

,type,setup,punchline,id
0,general,What's a computer's favorite snack?,Microchips.,423
1,general,What kind of bagel can fly?,A plain bagel.,251
2,programming,Why did the programmer quit their job?,They didn't get arrays.,437
3,general,Why are football stadiums so cool?,Because every seat has a fan in it.,404
4,general,Where was the Declaration of Independence signed?,At the bottom!,293
5,general,What kind of tree fits in your hand?,A palm tree!,257
6,general,What kind of award did the dentist receive?,A little plaque.,250
7,general,What do you call a cow with two legs?,Lean beef.,196
8,general,What is a witch's favorite subject in school?,Spelling!,242
9,general,Why did the cookie go to the doctor?,Because it was feeling crumbly.,434

In [18]:
df.to_csv("jokes.csv")
dfp = pd.read_csv("jokes.csv")
dfp

,Unnamed: 0,type,setup,punchline,id
0,0,general,What's a computer's favorite snack?,Microchips.,423
1,1,general,What kind of bagel can fly?,A plain bagel.,251
2,2,programming,Why did the programmer quit their job?,They didn't get arrays.,437
3,3,general,Why are football stadiums so cool?,Because every seat has a fan in it.,404
4,4,general,Where was the Declaration of Independence signed?,At the bottom!,293
5,5,general,What kind of tree fits in your hand?,A palm tree!,257
6,6,general,What kind of award did the dentist receive?,A little plaque.,250
7,7,general,What do you call a cow with two legs?,Lean beef.,196
8,8,general,What is a witch's favorite subject in school?,Spelling!,242
9,9,general,Why did the cookie go to the doctor?,Because it was feeling crumbly.,434

In [14]:
df.to_pickle("jokes.pkl")

In [17]:
dfp = pd.read_pickle("jokes.pkl") 
dfp

,type,setup,punchline,id
0,general,What's a computer's favorite snack?,Microchips.,423
1,general,What kind of bagel can fly?,A plain bagel.,251
2,programming,Why did the programmer quit their job?,They didn't get arrays.,437
3,general,Why are football stadiums so cool?,Because every seat has a fan in it.,404
4,general,Where was the Declaration of Independence signed?,At the bottom!,293
5,general,What kind of tree fits in your hand?,A palm tree!,257
6,general,What kind of award did the dentist receive?,A little plaque.,250
7,general,What do you call a cow with two legs?,Lean beef.,196
8,general,What is a witch's favorite subject in school?,Spelling!,242
9,general,Why did the cookie go to the doctor?,Because it was feeling crumbly.,434