In [3]:
import pandas as pd
df = pd.read_csv(r'C:\Users\Akmal Khan\OneDrive\Desktop\Data Science\first.csv',index_col=0)

In [4]:
df.head()

     A   B   C   D
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [10]:
df.iloc[:3, 0:1]

    A
r1  0
r2  4
r3  8

In [9]:
df.iloc[[0,2,3], 0] #returns a series

r1     0
r3     8
r4    12
Name: A, dtype: int64

In [12]:
df.loc['r1'] #here 0 wont work as the label of row is r1

A    0
B    1
C    2
D    3
Name: r1, dtype: int64

In [15]:
anime_df = pd.DataFrame({
	"Title": ["Naruto", "One Piece", "Attack on Titan", "Demon Slayer", "Death Note"],
	"Genre": ["Action", "Adventure", "Action", "Fantasy", "Thriller"],
	"Episodes": [220, 1000, 87, 55, 37],
	"Rating": [7.9, 8.7, 9.0, 8.7, 8.6]
})

anime_df.to_csv("anime.csv", index=False)
anime_df

             Title      Genre  Episodes  Rating
0           Naruto     Action       220     7.9
1        One Piece  Adventure      1000     8.7
2  Attack on Titan     Action        87     9.0
3     Demon Slayer    Fantasy        55     8.7
4       Death Note   Thriller        37     8.6

In [18]:
anime_df.loc[:3, ['Title','Episodes', 'Rating']] #notice how even 3 is included  that is the diff between loc and iloc

             Title  Episodes  Rating
0           Naruto       220     7.9
1        One Piece      1000     8.7
2  Attack on Titan        87     9.0
3     Demon Slayer        55     8.7

In [20]:
anime_df.Rating >= 8.7

0    False
1     True
2     True
3     True
4    False
Name: Rating, dtype: bool

In [22]:
anime_df.loc[anime_df.Rating >= 8.7, ['Title', 'Rating']] #only the true indexes passed for rows

             Title      Genre  Episodes  Rating
1        One Piece  Adventure      1000     8.7
2  Attack on Titan     Action        87     9.0
3     Demon Slayer    Fantasy        55     8.7

In [25]:
anime_df.loc[(anime_df.Rating >8) | (anime_df.Episodes < 100)]

             Title      Genre  Episodes  Rating
1        One Piece  Adventure      1000     8.7
2  Attack on Titan     Action        87     9.0
3     Demon Slayer    Fantasy        55     8.7
4       Death Note   Thriller        37     8.6

In [28]:
nulld = pd.DataFrame({
	"Name": ["Alice", "Bob", None, "David", "Eva"],
	"Age": [25, None, 35, 40, None],
	"City": ["New York", "London", "Paris", None, "Tokyo"],
	"Score": [88, 92, None, 75, 81]
})

nulld

    Name   Age      City  Score
0  Alice  25.0  New York   88.0
1    Bob   NaN    London   92.0
2    NaN  35.0     Paris    NaN
3  David  40.0       NaN   75.0
4    Eva   NaN     Tokyo   81.0

In [29]:
nulld.loc[nulld.Age.isnull()]

  Name  Age    City  Score
1  Bob  NaN  London   92.0
4  Eva  NaN   Tokyo   81.0

In [30]:
nulld.loc[nulld.Age.notnull()]

    Name   Age      City  Score
0  Alice  25.0  New York   88.0
2    NaN  35.0     Paris    NaN
3  David  40.0       NaN   75.0

In [35]:
us = nulld.loc[nulld.City.isin(['New York', 'London'])]
us

    Name   Age      City  Score
0  Alice  25.0  New York   88.0
1    Bob   NaN    London   92.0