In [6]:
import pandas as pd
from io import StringIO
data = ('c1,c2,c3\n'
				'a,b,c\n'
				'1,2,3\n'
				'4,5,6\n')

df = pd.read_csv(StringIO(data), usecols=['c1', 'c2'], dtype={'c1': str, 'c2': object})
print(df)

  c1 c2
0  a  b
1  1  2
2  4  5

In [ ]:
data2 = ('c1,c2,c3\n'
				'8,9,a,10\n'
				'1,2,b,3\n'
				'4,5,c,6\n')

df2 = pd.read_csv(StringIO(data2), index_col=2) 
df2

   c1  c2  c3
a   8   9  10
b   1   2   3
c   4   5   6

In [12]:
data3 = ('c1,c2,index,c3\n'
				'8,9,a,10\n'
				'1,2,b,3\n'
				'4,5,c,6\n')
df3 = pd.read_csv(StringIO(data3), index_col='index') 
df3

       c1  c2  c3
index
a       8   9  10
b       1   2   3
c       4   5   6

In [18]:
data3 = ('c1,c2,c3\n'
				'8,a,b\n'
				'1,d,e\n'
				'4,g,h\n')

df3 = pd.read_csv(StringIO(data3))
df3

   c1 c2 c3
0   8  a  b
1   1  d  e
2   4  g  h